export default {
    RESET_STATE: 'RESET_STATE',
    SET_TMDB_CONFIGURATION: 'SET_TMDB_CONFIGURATION',
    SET_QUERY_TERM: 'SET_QUERY_TERM',
    INITIATE_SEARCH: 'INITIATE_SEARCH',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_SEARCH_HAS_RESULTS: 'SET_SEARCH_HAS_RESULTS',
    SET_SHOW_BACKDROP: 'SET_SHOW_BACKDROP'
};
