export default {
    SET_TMDB_CONFIGURATION: 'SET_TMDB_CONFIGURATION',
    SET_QUERY_TERM: 'SET_QUERY_TERM',
    INITIATE_SEARCH: 'INITIATE_SEARCH',
    SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
    SET_SEARCH_HAS_RESULTS: 'SET_SEARCH_HAS_RESULTS'
};
